# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - readme.md
      - LICENSE
      - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: keystore
  displayName: Download keystore file
  inputs:
    retryCount: 3
    secureFile: keystore.jks

- task: DownloadSecureFile@1
  name: googleservice
  displayName: Download Firebase configuration
  inputs: 
   retryCount: 3
   secureFile: google-services.json
   
- script: |
    sudo chmod +x gradlew
    sudo chown root:root $(googleservice.secureFilePath)
    sudo chmod a+r $(googleservice.secureFilePath)
    cp $(googleservice.secureFilePath) app/
  displayName: Setup Firebase configuration

- task: Gradle@3
  displayName: Build apk
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    jdkVersionOption: '1.17'
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- script: |
    sudo java tools/CiSign.java
  displayName: Pre-sign apk

- task: AndroidSigning@3
  displayName: Signing apk
  inputs:
    apkFiles: 'app/signTarget/*.apk'
    apksignerKeystoreFile: 'keystore.jks'
    apksignerKeystorePassword: $(keystorePassword)
    apksignerKeystoreAlias: 'release'
    apksignerKeyPassword: $(keyPassword)

- task: PublishBuildArtifacts@1
displayName: Upload artifact
inputs:
  PathtoPublish: 'app/signTarget'
  ArtifactName: 'EveryPush'
  publishLocation: 'Container'
    
