# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - readme.md
      - LICENSE
      - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  inputs:
    retryCount: 3
    secureFile: keystore.jks
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: AndroidSigning@3
  inputs:
    apkFiles: 'app/build/outputs/apk/release/app-release-unsigned.apk'
    apksignerKeystoreFile: 'keystore.jks'
    apksignerKeystorePassword: $(keystorePassword)
    apksignerKeystoreAlias: 'release'
    apksignerKeyPassword: $(keyPassword)
- script: |
    sudo cp app/release/app-release-unsigned.apk $(Build.ArtifactStagingDirectory)/app-release.apk
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'EveryPush'
    publishLocation: 'Container'
    
